spring:

  #  Email config
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    add-properties: false
  application:
    name: brightlife
    liquibase:
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true

  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Disable automatic table creation
  jpa:
    hibernate:
      ddl-auto: update

    # Show SQL in logs
    show-sql: true
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: ${OAUTH_CERT_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /brightlife_api_contract.yaml
    config-url: /v3/api-docs/swagger-config

server:
  port: ${SERVER_PORT}
#  ssl:
#    enabled: true
#    key-store: file:/opt/brightlife_app/brightlife.p12  # Path on EC2, NOT your local!
#    key-store-password: ${KEY_STORE_PASSWORD}
#    key-store-type: ${KEY_STORE_TYPE}
#    key-alias: ${KEY_ALIAS}
#http:
#  port: ${HTTP_PORT}

token:
  expirationms: 3600000
  secret:
    key: ${TOKEN_SECRET_KEY}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  bucket-name: ${S3_BUCKET_NAME}
  region: ${AWS_REGION}

fe:
  base:
    url: ${FE_BASE_URL}