spring:
  devtools:
    add-properties: false
  application:
    name: brightlife
    liquibase:
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true

  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Disable automatic table creation
  jpa:
    hibernate:
      ddl-auto: create

    # Show SQL in logs
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: ${OAUTH_CERT_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /brightlife_api_contract.yaml
    config-url: /v3/api-docs/swagger-config

server:
  #  port: 8085
  port: ${SERVER_PORT}
token:
  expirationms: 3600000
  secret:
    key: ${TOKEN_SECRET_KEY}



